import { Case, LabDocument, Order } from "@core/models";
import { getCaseDocuments, getCaseOrders } from "./case-relations";

const CASE: Case = {
  id: "case-1",
  caseNumber: "CS-08101",
  title: "Full Arch Restoration — Alice Johnson",
  patientId: "pt1",
  patientName: "Alice Johnson",
  doctorId: "dr1",
  doctorName: "Dr. Allison Park",
  clinicId: "cl1",
  clinicName: "Bright Smile Dental",
  status: "Open",
  priority: "High",
  ordersCount: 3,
  filesCount: 8,
  createdAt: "2024-11-10T10:00:00Z",
  updatedAt: "2024-12-10T14:00:00Z",
  notes: "",
};

const ORDERS: Order[] = [
  {
    id: "ord-1",
    orderNumber: "DL-024001",
    patientId: "pt1",
    patientName: "Alice Johnson",
    doctorId: "dr1",
    doctorName: "Dr. Allison Park",
    clinicId: "cl1",
    clinicName: "Bright Smile Dental",
    scanCenterId: "sc1",
    scanCenterName: "SC-LA Central",
    status: "New",
    priority: "Normal",
    restoration: "Crown",
    arch: "Maxilla",
    format: "STL",
    shade: "A2",
    units: 1,
    amount: 450,
    billed: false,
    billTo: "Bright Smile Dental",
    vouchers: 0,
    isLocked: false,
    hasNotes: false,
    notes: "",
    receivedAt: "2024-12-10T10:00:00Z",
    updatedAt: "2024-12-10T10:00:00Z",
    dueDate: "2024-12-24",
  },
  {
    id: "ord-2",
    orderNumber: "DL-024002",
    patientId: "pt1",
    patientName: "Alice Johnson",
    doctorId: "dr1",
    doctorName: "Dr. Allison Park",
    clinicId: "cl1",
    clinicName: "Bright Smile Dental",
    scanCenterId: "sc1",
    scanCenterName: "SC-LA Central",
    status: "Review",
    priority: "High",
    restoration: "Bridge",
    arch: "Mandible",
    format: "STL",
    shade: "B1",
    units: 3,
    amount: 1200,
    billed: true,
    billedAmount: 1200,
    billTo: "Alice Johnson",
    vouchers: 1,
    isLocked: false,
    hasNotes: true,
    notes: "Shade verified",
    receivedAt: "2024-12-08T14:30:00Z",
    sentAt: "2024-12-09T09:00:00Z",
    updatedAt: "2024-12-11T09:00:00Z",
    chargedAt: "2024-12-09T09:00:00Z",
    dueDate: "2024-12-22",
  },
  {
    id: "ord-3",
    orderNumber: "DL-024003",
    patientId: "pt2",
    patientName: "Benjamin Clarke",
    doctorId: "dr2",
    doctorName: "Dr. Marcus Webb",
    clinicId: "cl2",
    clinicName: "Pacific Dental Group",
    scanCenterId: "sc2",
    scanCenterName: "SC-SD Harbor",
    status: "Design",
    priority: "Urgent",
    restoration: "Implant Crown",
    arch: "Maxilla",
    format: "STL+OBJ",
    shade: "A1",
    units: 1,
    amount: 850,
    billed: false,
    billTo: "Pacific Dental Group",
    vouchers: 0,
    isLocked: true,
    hasNotes: true,
    notes: "Urgent",
    receivedAt: "2024-12-12T08:00:00Z",
    sentAt: "2024-12-12T10:00:00Z",
    updatedAt: "2024-12-12T15:00:00Z",
    dueDate: "2024-12-18",
  },
];

const DOCUMENTS: LabDocument[] = [
  {
    id: "d1",
    name: "linked_by_order.stl",
    category: "Scan Files",
    type: "STL",
    size: "4 MB",
    date: "2024-12-11",
    doctor: "Dr. Other",
    orderId: "ord-1",
  },
  {
    id: "d2",
    name: "linked_by_patient.zip",
    category: "Patient Photos",
    type: "ZIP",
    size: "12 MB",
    date: "2024-12-12",
    doctor: "Dr. Other",
    patientName: "Alice Johnson",
  },
  {
    id: "d3",
    name: "linked_by_doctor.pdf",
    category: "Prescriptions",
    type: "PDF",
    size: "120 KB",
    date: "2024-12-13",
    doctor: "Dr. Allison Park",
  },
  {
    id: "d4",
    name: "not_linked.pdf",
    category: "Reports",
    type: "PDF",
    size: "100 KB",
    date: "2024-12-14",
    doctor: "Dr. Marcus Webb",
    patientName: "Benjamin Clarke",
  },
];

describe("case-relations", () => {
  it("should return case orders sorted by updatedAt descending", () => {
    const result = getCaseOrders(CASE, ORDERS);
    expect(result.map((order) => order.id)).toEqual(["ord-2", "ord-1"]);
  });

  it("should collect documents related by order or patient", () => {
    const caseOrders = getCaseOrders(CASE, ORDERS);
    const result = getCaseDocuments(CASE, caseOrders, DOCUMENTS);
    expect(result.map((doc) => doc.id)).toEqual(["d2", "d1"]);
  });
});
